import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

import { ValidationError } from "../../shared/errors.js";
import {
  CODE_WIKI_LEGACY_GENERATED_PATHS,
  CODE_WIKI_PAGE_DEFINITIONS,
  REFINED_PAGES_INDEX_SCAFFOLD,
  type CodeWikiCategory,
  type CodeWikiPageDefinition,
} from "./code-wiki-page-definitions.js";
import { collectCodeWikiRepoSnapshot } from "./code-wiki-repo-snapshot.js";
import { walkFiles } from "../shared/walk-files.js";
import {
  DEFAULT_CODE_WIKI_ROOT,
  relativeToRepoRoot,
  relativeToWikiRoot,
  resolveCodeWikiPaths,
  toPosixPath,
  type CodeWikiPaths,
} from "../shared/wiki-paths.js";

export interface CodeWikiServiceDependencies {
  cwd?: string;
  now?: () => Date;
}

export interface CodeWikiMutationResult {
  wikiRoot: string;
  updatedPages: string[];
  logPath: string;
}

export interface CodeWikiQueryMatch {
  path: string;
  title: string;
  summary: string;
  score: number;
  snippet: string;
}

export interface CodeWikiLintResult {
  wikiRoot: string;
  reportPath: string;
  missingRequiredPages: string[];
  unindexedPages: string[];
  orphanPages: string[];
  brokenLinks: string[];
}

interface SearchableWikiPage {
  path: string;
  title: string;
  summary: string;
  body: string;
}

interface LintFindings {
  missingRequiredPages: string[];
  unindexedPages: string[];
  orphanPages: string[];
  brokenLinks: string[];
}

const MARKDOWN_LINK_PATTERN = /\[[^\]]+\]\(([^)]+)\)/gu;

function matchSourcePath(sourcePath: string, prefix: string): boolean {
  if (sourcePath === prefix) {
    return true;
  }

  if (prefix.endsWith(".md")) {
    return sourcePath === prefix;
  }

  return sourcePath.startsWith(`${prefix}/`);
}

function uniqueSorted(values: readonly string[]): string[] {
  return [...new Set(values)].sort();
}

function normalizeSourcePaths(sourcePaths: readonly string[]): string[] {
  return uniqueSorted(
    sourcePaths
      .map((sourcePath) => toPosixPath(sourcePath.trim()))
      .filter((sourcePath) => sourcePath.length > 0)
      .map((sourcePath) => sourcePath.replace(/^\.\//u, "")),
  );
}

function evidenceDefinitions(): CodeWikiPageDefinition[] {
  return CODE_WIKI_PAGE_DEFINITIONS.filter((definition) => definition.path.startsWith("evidence/"));
}

function toEvidenceRelativePath(path: string): string {
  return path.replace(/^evidence\//u, "");
}

function renderEvidenceIndexSection(title: string, definitions: readonly CodeWikiPageDefinition[]): string {
  if (definitions.length === 0) {
    return "";
  }

  return [
    `## ${title}`,
    "",
    ...definitions.map((definition) => {
      const link = `./${toEvidenceRelativePath(definition.path)}`;
      const sources = definition.sourcePaths.map((sourcePath) => `\`${sourcePath}\``).join(", ");
      return `- [${definition.title}](${link}): ${definition.summary} Sources: ${sources}.`;
    }),
    "",
  ].join("\n");
}

const EVIDENCE_INDEX_SECTIONS: ReadonlyArray<{ title: string; category: CodeWikiCategory }> = [
  { title: "Foundations", category: "foundation" },
  { title: "Modules", category: "module" },
  { title: "Workflows", category: "workflow" },
  { title: "Quality", category: "quality" },
];

function renderEvidenceIndexDocument(): string {
  const byCategory = new Map<CodeWikiCategory, CodeWikiPageDefinition[]>(
    EVIDENCE_INDEX_SECTIONS.map((section) => [section.category, []]),
  );

  for (const definition of evidenceDefinitions()) {
    byCategory.get(definition.category)?.push(definition);
  }

  return [
    "# Evidence Index",
    "",
    "This index catalogs the deterministic evidence generated by the wiki CLI. Use these pages as raw material for refined documentation under `../pages/`.",
    "",
    ...EVIDENCE_INDEX_SECTIONS.map((section) => {
      return renderEvidenceIndexSection(section.title, byCategory.get(section.category) ?? []);
    }),
  ].join("\n");
}

function renderRootIndexDocument(): string {
  return [
    "# Code Wiki Index",
    "",
    "This wiki has two layers: deterministic evidence in `./evidence/` and LLM-maintained synthesis in `./pages/`.",
    "",
    "## Start Here",
    "",
    "- [Code Wiki Schema](./schema.md): ownership model, workflows, and constraints for the whole wiki.",
    "- [LLM Refinement Playbook](./refinement-playbook.md): rigid instructions for converting evidence into refined docs.",
    "- [Refined Pages Index](./pages/index.md): catalog of synthesized pages maintained by an LLM or a human.",
    "- [Evidence Index](./evidence/index.md): catalog of deterministic evidence pages generated by the CLI.",
    "- [Log](./log.md): append-only history of deterministic and refinement operations.",
    "",
    "## Query Rule",
    "",
    "- Run `npm run wiki -- query --query \"<terms>\"` for broad questions.",
    "- Prefer `./pages/` when a refined page exists.",
    "- Verify important claims against `./evidence/` and then raw code when behavior is ambiguous or stale.",
    "",
  ].join("\n");
}

function renderLogHeader(): string {
  return [
    "# Code Wiki Log",
    "",
    "Append-only record of deterministic wiki maintenance operations and LLM refinement passes.",
    "",
  ].join("\n");
}

interface ParsedFrontmatter {
  frontmatter: string;
  body: string;
}

function splitFrontmatter(content: string): ParsedFrontmatter | null {
  if (!content.startsWith("---\n")) {
    return null;
  }

  const closingIndex = content.indexOf("\n---\n", 4);

  if (closingIndex === -1) {
    return null;
  }

  return {
    frontmatter: content.slice(4, closingIndex),
    body: content.slice(closingIndex + 5),
  };
}

function stripFrontmatter(content: string): string {
  return splitFrontmatter(content)?.body ?? content;
}

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .split(/[^a-z0-9]+/u)
    .map((token) => token.trim())
    .filter((token) => token.length > 0);
}

function computeLayerBoost(path: string): number {
  if (path.startsWith("pages/")) {
    return 2;
  }

  if (path.startsWith("evidence/")) {
    return 1;
  }

  return 0;
}

function buildSnippet(body: string, terms: readonly string[]): string {
  const normalizedBody = stripFrontmatter(body).replace(/\s+/gu, " ").trim();

  if (normalizedBody.length === 0) {
    return "";
  }

  const lowerBody = normalizedBody.toLowerCase();

  for (const term of terms) {
    const foundIndex = lowerBody.indexOf(term);

    if (foundIndex !== -1) {
      const startIndex = Math.max(0, foundIndex - 80);
      const endIndex = Math.min(normalizedBody.length, foundIndex + term.length + 120);
      return normalizedBody.slice(startIndex, endIndex).trim();
    }
  }

  return normalizedBody.slice(0, 200).trim();
}

function parseMarkdownLinks(content: string): string[] {
  const links: string[] = [];

  for (const match of content.matchAll(MARKDOWN_LINK_PATTERN)) {
    const rawTarget = match[1]?.trim();

    if (rawTarget === undefined || rawTarget.length === 0) {
      continue;
    }

    if (rawTarget.startsWith("http://") || rawTarget.startsWith("https://")) {
      continue;
    }

    const targetWithoutAnchor = rawTarget.split("#", 1)[0] ?? "";
    const normalizedTarget = targetWithoutAnchor.replace(/^<|>$/gu, "");

    if (normalizedTarget.length === 0) {
      continue;
    }

    links.push(normalizedTarget);
  }

  return links;
}

function readFrontmatterField(content: string, field: string): string | null {
  const parsed = splitFrontmatter(content);

  if (parsed === null) {
    return null;
  }

  const frontmatter = parsed.frontmatter;
  const pattern = new RegExp(`^${field}:\\s*(.+)$`, "mu");
  const match = frontmatter.match(pattern);
  const value = match?.[1]?.trim();

  if (value === undefined || value.length === 0) {
    return null;
  }

  return value.replace(/^"(.*)"$/u, "$1");
}

function extractFirstHeading(content: string): string | null {
  const body = stripFrontmatter(content);

  for (const line of body.split("\n")) {
    const trimmed = line.trim();

    if (trimmed.startsWith("# ")) {
      return trimmed.slice(2).trim();
    }
  }

  return null;
}

function extractSummary(content: string): string {
  const frontmatterSummary = readFrontmatterField(content, "summary");

  if (frontmatterSummary !== null) {
    return frontmatterSummary;
  }

  const body = stripFrontmatter(content)
    .replace(MARKDOWN_LINK_PATTERN, "$1")
    .replace(/`([^`]+)`/gu, "$1");

  for (const line of body.split("\n")) {
    const trimmed = line.trim();

    if (trimmed.length === 0 || trimmed.startsWith("#")) {
      continue;
    }

    return trimmed.replace(/\s+/gu, " ").slice(0, 180);
  }

  return "";
}

function derivePageTitle(pagePath: string, content: string): string {
  return readFrontmatterField(content, "title")
    ?? extractFirstHeading(content)
    ?? pagePath;
}

async function writeTextFile(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

async function listMarkdownFiles(rootDir: string): Promise<string[]> {
  return await walkFiles(rootDir, {
    filter: (absolutePath) => absolutePath.endsWith(".md"),
    map: (absolutePath) => toPosixPath(absolutePath),
  });
}

export class CodeWikiService {
  private readonly repoRoot: string;
  private readonly now: () => Date;

  public constructor(dependencies: CodeWikiServiceDependencies = {}) {
    this.repoRoot = resolve(dependencies.cwd ?? process.cwd());
    this.now = dependencies.now ?? (() => new Date());
  }

  public async init(wikiRoot = DEFAULT_CODE_WIKI_ROOT): Promise<CodeWikiMutationResult> {
    return await this.writeAllPages("init", wikiRoot);
  }

  public async refresh(wikiRoot = DEFAULT_CODE_WIKI_ROOT): Promise<CodeWikiMutationResult> {
    return await this.writeAllPages("refresh", wikiRoot);
  }

  private async writeAllPages(action: "init" | "refresh", wikiRoot: string): Promise<CodeWikiMutationResult> {
    const titles = {
      init: "Code Wiki Bootstrap",
      refresh: "Code Wiki Refresh",
    } as const;
    const detailPrefixes = {
      init: "Pages generated",
      refresh: "Pages refreshed",
    } as const;

    return await this.writePages({
      wikiRoot,
      action,
      title: titles[action],
      detailPrefix: detailPrefixes[action],
      definitions: CODE_WIKI_PAGE_DEFINITIONS,
    });
  }

  public async ingest(sourcePaths: readonly string[], wikiRoot = DEFAULT_CODE_WIKI_ROOT): Promise<CodeWikiMutationResult> {
    const normalizedSources = normalizeSourcePaths(sourcePaths);

    if (normalizedSources.length === 0) {
      throw new ValidationError("Comando ingest exige ao menos um --source.", "wiki");
    }

    const affectedDefinitions = CODE_WIKI_PAGE_DEFINITIONS.filter((definition) => {
      return normalizedSources.some((sourcePath) => {
        return definition.sourcePaths.some((prefix) => matchSourcePath(sourcePath, prefix));
      });
    });

    const definitions = affectedDefinitions.length > 0
      ? affectedDefinitions
      : CODE_WIKI_PAGE_DEFINITIONS.filter((definition) => definition.path === "evidence/overview.md");

    return await this.writePages({
      wikiRoot,
      action: "ingest",
      title: normalizedSources.join(", "),
      detailPrefix: "Sources",
      detailValues: normalizedSources.map((sourcePath) => `\`${sourcePath}\``),
      definitions,
    });
  }

  public async query(searchText: string, wikiRoot = DEFAULT_CODE_WIKI_ROOT, limit = 5): Promise<CodeWikiQueryMatch[]> {
    const normalizedQuery = searchText.trim();

    if (normalizedQuery.length === 0) {
      throw new ValidationError("Comando query exige --query com texto nao vazio.", "wiki");
    }

    const paths = resolveCodeWikiPaths(this.repoRoot, wikiRoot);
    const pages = await this.loadSearchablePages(paths);
    const terms = tokenize(normalizedQuery);

    return pages
      .map((page) => {
        const searchableText = `${page.title} ${page.summary} ${stripFrontmatter(page.body)}`.toLowerCase();
        const termScore = terms.reduce((total, term) => total + (searchableText.split(term).length - 1), 0);
        const layerBoost = computeLayerBoost(page.path);

        return {
          path: page.path,
          title: page.title,
          summary: page.summary,
          score: termScore === 0 ? 0 : (termScore * 10) + layerBoost,
          snippet: buildSnippet(page.body, terms),
        };
      })
      .filter((match) => match.score > 0)
      .sort((left, right) => {
        if (right.score !== left.score) {
          return right.score - left.score;
        }

        return left.path.localeCompare(right.path);
      })
      .slice(0, limit);
  }

  public async lint(wikiRoot = DEFAULT_CODE_WIKI_ROOT): Promise<CodeWikiLintResult> {
    const paths = resolveCodeWikiPaths(this.repoRoot, wikiRoot);
    const findings = await this.collectLintFindings(paths);

    await this.persistLintReport(paths, findings);

    return {
      wikiRoot: relativeToRepoRoot(this.repoRoot, paths.rootDir),
      reportPath: relativeToRepoRoot(this.repoRoot, paths.lintReportPath),
      missingRequiredPages: findings.missingRequiredPages,
      unindexedPages: findings.unindexedPages,
      orphanPages: findings.orphanPages,
      brokenLinks: findings.brokenLinks,
    };
  }

  private async collectLintFindings(paths: CodeWikiPaths): Promise<LintFindings> {
    const absoluteMarkdownFiles = await listMarkdownFiles(paths.rootDir);
    const pagePaths = absoluteMarkdownFiles
      .map((absolutePath) => relativeToWikiRoot(paths, absolutePath))
      .filter((path) => !path.startsWith("reports/"));
    const pagePathSet = new Set(pagePaths);
    const requiredPaths = new Set([
      "index.md",
      "log.md",
      "pages/index.md",
      ...CODE_WIKI_PAGE_DEFINITIONS.map((definition) => definition.path),
    ]);
    const contents = new Map<string, string>();

    for (const pagePath of pagePaths) {
      contents.set(pagePath, await readFile(join(paths.rootDir, pagePath), "utf8"));
    }

    const missingRequiredPages = [...requiredPaths].filter((path) => !pagePathSet.has(path)).sort();
    const indexPages = pagePaths.filter((pagePath) => pagePath === "index.md" || pagePath.endsWith("/index.md"));
    const indexedPages = new Set<string>();

    for (const indexPage of indexPages) {
      const indexContent = contents.get(indexPage) ?? "";
      const absoluteIndexPath = join(paths.rootDir, indexPage);

      for (const target of parseMarkdownLinks(indexContent)) {
        indexedPages.add(relativeToWikiRoot(paths, resolve(dirname(absoluteIndexPath), target)));
      }
    }

    const unindexedPages = pagePaths
      .filter((pagePath) => pagePath !== "index.md")
      .filter((pagePath) => !indexedPages.has(pagePath))
      .sort();
    const inboundCounts = new Map<string, number>();
    const brokenLinks: string[] = [];

    for (const [pagePath, content] of contents.entries()) {
      const absolutePagePath = join(paths.rootDir, pagePath);

      for (const target of parseMarkdownLinks(content)) {
        const resolvedTarget = relativeToWikiRoot(paths, resolve(dirname(absolutePagePath), target));

        if (pagePathSet.has(resolvedTarget)) {
          inboundCounts.set(resolvedTarget, (inboundCounts.get(resolvedTarget) ?? 0) + 1);
          continue;
        }

        if (!(await fileExists(resolve(dirname(absolutePagePath), target)))) {
          brokenLinks.push(`${pagePath} -> ${target}`);
        }
      }
    }

    const orphanPages = pagePaths
      .filter((pagePath) => pagePath !== "index.md" && pagePath !== "log.md")
      .filter((pagePath) => (inboundCounts.get(pagePath) ?? 0) === 0)
      .sort();

    return {
      missingRequiredPages,
      unindexedPages,
      orphanPages,
      brokenLinks: uniqueSorted(brokenLinks),
    };
  }

  private async persistLintReport(paths: CodeWikiPaths, findings: LintFindings): Promise<void> {
    const report = this.renderLintReport(findings);

    await mkdir(paths.reportsDir, { recursive: true });
    await writeTextFile(paths.lintReportPath, report);
    await this.appendLogEntry(paths, "lint", "Code Wiki Health Check", [
      `- missing required pages: ${findings.missingRequiredPages.length}`,
      `- unindexed pages: ${findings.unindexedPages.length}`,
      `- orphan pages: ${findings.orphanPages.length}`,
      `- broken links: ${findings.brokenLinks.length}`,
    ]);
  }

  private async loadSearchablePages(paths: CodeWikiPaths): Promise<SearchableWikiPage[]> {
    const absoluteMarkdownFiles = await listMarkdownFiles(paths.rootDir);
    const searchablePaths = absoluteMarkdownFiles
      .map((absolutePath) => relativeToWikiRoot(paths, absolutePath))
      .filter((path) => !path.startsWith("reports/"));

    const pages: SearchableWikiPage[] = [];

    for (const pagePath of searchablePaths) {
      const body = await readFile(join(paths.rootDir, pagePath), "utf8");
      pages.push({
        path: pagePath,
        title: derivePageTitle(pagePath, body),
        summary: extractSummary(body),
        body,
      });
    }

    return pages;
  }

  private async writePages(input: {
    wikiRoot: string;
    action: "init" | "refresh" | "ingest";
    title: string;
    detailPrefix: string;
    definitions: readonly CodeWikiPageDefinition[];
    detailValues?: readonly string[];
  }): Promise<CodeWikiMutationResult> {
    const timestamp = this.now().toISOString();
    const snapshot = await collectCodeWikiRepoSnapshot(this.repoRoot, timestamp);
    const paths = resolveCodeWikiPaths(this.repoRoot, input.wikiRoot);

    await this.ensureDirectoryStructure(paths);
    await this.cleanupLegacyGeneratedFiles(paths);

    const updatedPages: string[] = [];

    for (const definition of input.definitions) {
      const absolutePath = join(paths.rootDir, definition.path);
      await writeTextFile(absolutePath, definition.build(snapshot));
      updatedPages.push(definition.path);
    }

    await writeTextFile(paths.indexPath, renderRootIndexDocument());
    updatedPages.push("index.md");
    await writeTextFile(paths.evidenceIndexPath, renderEvidenceIndexDocument());
    updatedPages.push("evidence/index.md");

    if (await this.ensureRefinedPagesIndex(paths)) {
      updatedPages.push("pages/index.md");
    }

    await this.ensureLog(paths);

    const updatedPagesList = updatedPages.map((pagePath) => `\`${pagePath}\``).join(", ");
    const detailLines = input.detailValues === undefined
      ? [`- ${input.detailPrefix}: ${updatedPagesList}`]
      : [
        `- ${input.detailPrefix}: ${input.detailValues.join(", ")}`,
        `- pages updated: ${updatedPagesList}`,
      ];

    await this.appendLogEntry(paths, input.action, input.title, detailLines);

    return {
      wikiRoot: relativeToRepoRoot(this.repoRoot, paths.rootDir),
      updatedPages: uniqueSorted(updatedPages),
      logPath: relativeToRepoRoot(this.repoRoot, paths.logPath),
    };
  }

  private async ensureDirectoryStructure(paths: CodeWikiPaths): Promise<void> {
    await Promise.all([
      mkdir(paths.rootDir, { recursive: true }),
      mkdir(paths.evidenceDir, { recursive: true }),
      mkdir(paths.evidenceModulesDir, { recursive: true }),
      mkdir(paths.evidenceWorkflowsDir, { recursive: true }),
      mkdir(paths.pagesDir, { recursive: true }),
      mkdir(paths.reportsDir, { recursive: true }),
    ]);
  }

  private async cleanupLegacyGeneratedFiles(paths: CodeWikiPaths): Promise<void> {
    await Promise.all(
      CODE_WIKI_LEGACY_GENERATED_PATHS.map(async (legacyPath) => {
        await rm(join(paths.rootDir, legacyPath), { force: true });
      }),
    );
  }

  private async ensureRefinedPagesIndex(paths: CodeWikiPaths): Promise<boolean> {
    if (await fileExists(paths.refinedIndexPath)) {
      return false;
    }

    await writeTextFile(paths.refinedIndexPath, REFINED_PAGES_INDEX_SCAFFOLD);
    return true;
  }

  private async ensureLog(paths: CodeWikiPaths): Promise<void> {
    if (await fileExists(paths.logPath)) {
      return;
    }

    await writeTextFile(paths.logPath, renderLogHeader());
  }

  private async appendLogEntry(
    paths: CodeWikiPaths,
    action: "init" | "refresh" | "ingest" | "lint",
    title: string,
    lines: readonly string[],
  ): Promise<void> {
    const date = this.now().toISOString().slice(0, 10);
    const base = await fileExists(paths.logPath)
      ? await readFile(paths.logPath, "utf8")
      : renderLogHeader();
    const normalizedBase = base.endsWith("\n") ? base : `${base}\n`;
    const entry = [
      `## [${date}] ${action} | ${title}`,
      "",
      ...lines,
      "",
    ].join("\n");

    await writeTextFile(paths.logPath, `${normalizedBase}${entry}`);
  }

  private renderLintReport(input: {
    missingRequiredPages: readonly string[];
    unindexedPages: readonly string[];
    orphanPages: readonly string[];
    brokenLinks: readonly string[];
  }): string {
    const sections: ReadonlyArray<{ heading: string; items: readonly string[] }> = [
      { heading: "Missing Required Pages", items: input.missingRequiredPages },
      { heading: "Unindexed Pages", items: input.unindexedPages },
      { heading: "Orphan Pages", items: input.orphanPages },
      { heading: "Broken Links", items: input.brokenLinks },
    ];
    const issueCount = sections.reduce((total, section) => total + section.items.length, 0);
    const status = issueCount === 0 ? "PASS" : "FAIL";

    return [
      "# Code Wiki Lint Report",
      "",
      `- status: ${status}`,
      `- generated_at: ${this.now().toISOString()}`,
      "",
      ...sections.flatMap((section) => [
        `## ${section.heading}`,
        "",
        ...(section.items.length === 0 ? ["- none"] : section.items.map((item) => `- \`${item}\``)),
        "",
      ]),
    ].join("\n");
  }
}
