import { CodeWikiRepoSnapshot } from "./code-wiki-repo-snapshot.js";

export type CodeWikiCategory = "foundation" | "module" | "workflow" | "quality";

export interface CodeWikiPageDefinition {
  path: string;
  title: string;
  category: CodeWikiCategory;
  summary: string;
  sourcePaths: string[];
  build(snapshot: CodeWikiRepoSnapshot): string;
}

function quoteYaml(value: string): string {
  return `"${value.replace(/"/gu, '\\"')}"`;
}

function renderFrontmatter(definition: CodeWikiPageDefinition): string {
  return [
    "---",
    `title: ${quoteYaml(definition.title)}`,
    `category: ${definition.category}`,
    `summary: ${quoteYaml(definition.summary)}`,
    "source_paths:",
    ...definition.sourcePaths.map((path) => `  - ${quoteYaml(path)}`),
    "---",
    "",
  ].join("\n");
}

function renderFileList(files: readonly string[]): string {
  if (files.length === 0) {
    return "- Nenhum arquivo encontrado neste recorte.";
  }

  return files.map((file) => `- \`${file}\``).join("\n");
}

function buildPage(definition: CodeWikiPageDefinition, body: string): string {
  return `${renderFrontmatter(definition)}${body.trim()}\n`;
}

function countText(label: string, count: number): string {
  return `- ${label}: ${count}`;
}

export const CODE_WIKI_LEGACY_GENERATED_PATHS = [
  "overview.md",
  "architecture.md",
  "testing.md",
  "modules/cli.md",
  "modules/application.md",
  "modules/domain.md",
  "modules/infrastructure.md",
  "modules/providers.md",
  "workflows/transcription-job.md",
  "workflows/resume-semantics.md",
] as const;

export const REFINED_PAGES_INDEX_SCAFFOLD = `# Refined Pages Index

This file is **LLM-maintained**. The deterministic wiki pipeline may create it if missing, but it must not overwrite human/LLM refinements afterwards.

## Foundations

- None yet.

## Modules

- None yet.

## Workflows

- None yet.

## Analyses

- None yet.

## Open Questions

- None yet.
`;

export const CODE_WIKI_PAGE_DEFINITIONS: readonly CodeWikiPageDefinition[] = [
  {
    path: "schema.md",
    title: "Code Wiki Schema",
    category: "foundation",
    summary: "Operating contract for the deterministic evidence layer and the LLM refinement layer.",
    sourcePaths: ["README.md", "AGENTS.md", "CLAUDE.md", "src", "tests", ".omx/plans", ".claude/project-context", ".agents/skills", ".claude/skills"],
    build(snapshot) {
      return buildPage(this, `
# Code Wiki Schema

This wiki documents the **codebase itself**. It does not track the semantic content produced by transcription jobs.

## Layers

- **Raw sources**: \`src/\`, \`tests/\`, \`README.md\`, \`.omx/plans/\`, \`.claude/project-context/\`, \`.agents/skills/\`, and \`.claude/skills/\`. These remain the source of truth.
- **Deterministic evidence**: \`docs/wiki/evidence/\`. Generated by the CLI. This layer is overwritten by \`init\`, \`refresh\`, and \`ingest\`.
- **Refined pages**: \`docs/wiki/pages/\`. Maintained by an LLM or a human. This layer is never overwritten by the deterministic CLI once scaffolded.
- **Schema**: this file plus [Refinement Playbook](./refinement-playbook.md). They define how future sessions should operate on the two layers.

## Canonical files

- [Index](./index.md): top-level navigation for the whole wiki.
- [Refinement Playbook](./refinement-playbook.md): rigid rules for turning evidence into durable project docs.
- [Evidence Index](./evidence/index.md): catalog of deterministic evidence pages.
- [Refined Pages Index](./pages/index.md): catalog of LLM-maintained refined pages.
- [Log](./log.md): append-only operational history covering deterministic updates and refinement passes.

## Ownership rules

- The CLI owns \`docs/wiki/evidence/\`, \`docs/wiki/schema.md\`, \`docs/wiki/refinement-playbook.md\`, the top-level \`index.md\`, and \`log.md\`.
- The LLM owns \`docs/wiki/pages/\` and should treat it as the durable synthesis layer.
- Never hand-edit \`docs/wiki/evidence/\`. If the evidence is stale, run \`npm run wiki -- ingest\` or \`npm run wiki -- refresh\`.
- Never let the deterministic CLI overwrite refined pages in \`docs/wiki/pages/\`.

## Deterministic workflow

### Init / Refresh

- Generate or refresh the evidence pages under \`docs/wiki/evidence/\`.
- Rebuild the top-level \`index.md\` and \`docs/wiki/evidence/index.md\`.
- Ensure \`docs/wiki/pages/index.md\` exists, but do not overwrite it if it already contains refined content.
- Append a chronological entry to \`log.md\`.

### Ingest

- Use \`npm run wiki -- ingest --source <path>\` after relevant code, test, or documentation changes.
- Update only evidence pages whose \`source_paths\` overlap the changed files.
- Rebuild the indexes owned by the deterministic layer.
- Append a chronological entry to \`log.md\`.

### Query

- Use \`npm run wiki -- query --query "<terms>"\` to search across both \`evidence/\` and \`pages/\`.
- Prefer refined pages when they exist, then verify against evidence pages and raw sources.
- When the scope is unclear, start from [Index](./index.md), then [Refined Pages Index](./pages/index.md), then [Evidence Index](./evidence/index.md).

### Lint

- Use \`npm run wiki -- lint\` to detect:
  - missing required deterministic pages
  - pages missing from any wiki index
  - orphan pages with no inbound wiki links
  - broken internal markdown links

## Refinement workflow

- Read [Refinement Playbook](./refinement-playbook.md) before writing or revising refined pages.
- Refine evidence into \`docs/wiki/pages/\`, not into \`docs/wiki/evidence/\`.
- If a session produces durable project knowledge, file it into \`docs/wiki/pages/\`, update \`docs/wiki/pages/index.md\`, and append a \`refine\` entry to \`log.md\`.

## Current repository snapshot

${countText("source files", snapshot.srcFiles.length)}
${countText("test files", snapshot.testFiles.length)}
${countText("plan/context artifacts", snapshot.planFiles.length + snapshot.contextFiles.length)}
      `);
    },
  },
  {
    path: "refinement-playbook.md",
    title: "LLM Refinement Playbook",
    category: "foundation",
    summary: "Rigid instructions for converting deterministic evidence into durable refined wiki pages.",
    sourcePaths: ["README.md", "AGENTS.md", "CLAUDE.md", "src/wiki", ".omx/plans", ".claude/project-context", ".agents/skills", ".claude/skills"],
    build() {
      return buildPage(this, `
# LLM Refinement Playbook

This file governs how an LLM should turn deterministic evidence into durable code documentation.

## Non-negotiable boundaries

- Never edit \`docs/wiki/evidence/\`. It is deterministic output owned by the CLI.
- Write all synthesis into \`docs/wiki/pages/\`.
- Do not treat deterministic evidence as automatically true forever. Verify against raw code when behavior, edge cases, or ownership are ambiguous.
- If evidence is stale, regenerate it before refining.

## Mandatory refinement sequence

1. Read [Schema](./schema.md), [Index](./index.md), [Refined Pages Index](./pages/index.md), and [Evidence Index](./evidence/index.md).
2. Run \`npm run wiki -- query --query "<terms>"\` for the topic being refined.
3. Read existing refined pages under \`docs/wiki/pages/\` first to avoid duplicate or conflicting narratives.
4. Read the supporting evidence pages under \`docs/wiki/evidence/\`.
5. Verify disputed or behavior-sensitive claims against raw sources in \`src/\`, \`tests/\`, \`README.md\`, \`.omx/plans/\`, or \`.claude/project-context/\`.
6. Create or update the refined page in \`docs/wiki/pages/\`.
7. Update \`docs/wiki/pages/index.md\` with a one-line summary for the refined page.
8. Append a log entry using the format \`## [YYYY-MM-DD] refine | <topic>\`.

## Required frontmatter for every refined page

\`\`\`yaml
---
title: "<Page title>"
summary: "<One-line summary>"
status: "draft" | "reviewed"
evidence_paths:
  - "../evidence/<path>.md"
source_paths:
  - "src/..."
  - "tests/..."
last_refined_on: "YYYY-MM-DD"
---
\`\`\`

## Required page sections

- \`# <Title>\`
- \`## What It Covers\`
- \`## How It Works\`
- \`## Evidence\`
- \`## Open Questions\`
- \`## Related Pages\`

## Claim discipline

- Every non-trivial claim must be justified by at least one evidence page and one raw source path.
- If a statement is an inference rather than an explicit fact, label it as \`Inference:\`.
- If the evidence is incomplete, record the gap under \`Open Questions\` instead of presenting a confident claim.
- Prefer stable architecture, boundaries, data contracts, and operational invariants over incidental implementation trivia.
- When two sources conflict, describe the conflict explicitly and identify which raw file needs confirmation.

## Mutation rules

- Add new refined pages only when the topic is durable and likely to be reused.
- Prefer updating an existing refined page instead of creating overlapping pages.
- Keep links relative so the wiki remains browsable in editors like Obsidian.
- Keep \`docs/wiki/pages/index.md\` current; it is the catalog for refined synthesis.
- Keep \`log.md\` chronological and append-only.

## Repo-local skills

- \`wiki-refinement-pass\`: full refinement pass from evidence into refined pages.
- \`wiki-promote-answer\`: promote a durable answer or comparison into the wiki.
- \`wiki-refinement-audit\`: review refined pages for playbook compliance and stale claims.

## When not to refine

- Do not create refined pages for one-off ephemeral chat answers.
- Do not restate deterministic evidence verbatim when no synthesis is needed.
- Do not create a refined page if the evidence layer is clearly stale and has not been regenerated yet.
      `);
    },
  },
  {
    path: "evidence/overview.md",
    title: "Deterministic Repository Evidence",
    category: "foundation",
    summary: "Auto-generated repository inventory and navigation hints for later LLM refinement.",
    sourcePaths: ["README.md", "package.json", "src", "tests"],
    build(snapshot) {
      return buildPage(this, `
# Deterministic Repository Evidence

This file is deterministic evidence generated from repository state. It is input for refinement, not the final refined narrative.

## Repository shape

- package: \`dnd-transcription\`
- runtime: Node.js + TypeScript
- primary product: CLI for chunking media, transcribing chunks, and merging a final markdown transcript

## Inventory counts

${countText("CLI files", snapshot.cliFiles.length)}
${countText("application files", snapshot.applicationFiles.length)}
${countText("domain files", snapshot.domainFiles.length)}
${countText("infrastructure files", snapshot.infrastructureFiles.length)}
${countText("provider files", snapshot.providerFiles.length)}
${countText("test files", snapshot.testFiles.length)}

## Generated evidence to read next

- [Architecture Evidence](./architecture.md)
- [CLI Module Evidence](./modules/cli.md)
- [Application Module Evidence](./modules/application.md)
- [Domain Module Evidence](./modules/domain.md)
- [Infrastructure Module Evidence](./modules/infrastructure.md)
- [Provider Adapter Evidence](./modules/providers.md)
- [Transcription Workflow Evidence](./workflows/transcription-job.md)
- [Resume Workflow Evidence](./workflows/resume-semantics.md)
- [Testing Evidence](./testing.md)

## Raw source coverage

- \`README.md\`
- \`package.json\`
- \`src/\`
- \`tests/\`
      `);
    },
  },
  {
    path: "evidence/architecture.md",
    title: "Architecture Evidence",
    category: "foundation",
    summary: "Auto-generated layer map, dependency direction, and source inventories.",
    sourcePaths: ["src/cli", "src/application", "src/domain", "src/infrastructure", "README.md", ".omx/plans/brownfield-map.md"],
    build(snapshot) {
      return buildPage(this, `
# Architecture Evidence

This file captures deterministic architectural evidence. Use it as a base for refined architecture documentation.

## Layer map

\`\`\`mermaid
flowchart TD
  CLI[CLI adapters\\nsrc/cli]
  APP[Application use cases\\nsrc/application]
  DOMAIN[Domain entities and ports\\nsrc/domain]
  INFRA[Infrastructure adapters\\nsrc/infrastructure]

  CLI --> APP
  APP --> DOMAIN
  APP --> INFRA
  INFRA --> DOMAIN
\`\`\`

## Boundary evidence

- CLI reads argv, resolves inputs, loads environment variables, and composes dependencies.
- Application owns orchestration and end-to-end control flow.
- Domain owns lifecycle rules, compatibility checks, and contracts.
- Infrastructure implements ports and isolates filesystem, subprocess, SDK, and network details.

## File inventories

### CLI

${renderFileList(snapshot.cliFiles)}

### Application

${renderFileList(snapshot.applicationFiles)}

### Domain

${renderFileList(snapshot.domainFiles)}

### Infrastructure

${renderFileList(snapshot.infrastructureFiles)}
      `);
    },
  },
  {
    path: "evidence/modules/cli.md",
    title: "CLI Module Evidence",
    category: "module",
    summary: "Observed responsibilities, seams, and file inventory for the CLI layer.",
    sourcePaths: ["src/cli", "src/shared/env-file.ts", "README.md"],
    build(snapshot) {
      return buildPage(this, `
# CLI Module Evidence

This file is deterministic evidence for the CLI layer.

## Observed responsibilities

- expose the Node entrypoint via \`src/cli/main.ts\`
- parse and validate flags in \`src/cli/cli-argument-parser.ts\`
- normalize \`--input\` with \`src/cli/input-path-resolver.ts\`
- load \`.env\` without overriding exported shell variables
- create the default transcriber binding lazily based on the selected provider

## Dependency seams kept for tests

- \`createJobStore\`
- \`createMediaSegmenter\`
- \`createTranscriberBinding\`
- \`createTranscriber\`
- \`createOpenAIAudioClient\`
- \`cwd\`

## Observed behavior

- Help returns before env loading or use-case execution.
- The CLI does not materialize the real transcriber when a resumed job is already \`succeeded\`.
- Unknown providers fail in the binding factory, not deep inside the pipeline.

## Relevant files

${renderFileList(snapshot.cliFiles)}
      `);
    },
  },
  {
    path: "evidence/modules/application.md",
    title: "Application Module Evidence",
    category: "module",
    summary: "Observed orchestration steps and files for the application layer.",
    sourcePaths: ["src/application", "src/infrastructure/concurrency/task-pool.ts"],
    build(snapshot) {
      return buildPage(this, `
# Application Module Evidence

This file is deterministic evidence for the application layer.

## Main use cases

- \`RunTranscriptionJobUseCase\`: full pipeline orchestration
- \`MergeTranscriptsUseCase\`: final markdown assembly from persisted chunk outputs

## Observed orchestration steps

1. Create a compatibility snapshot from the input file, provider, signature, and chunk duration.
2. Decide between new job bootstrap or \`--resume\`.
3. Segment media and hydrate pending chunks for new jobs.
4. Move the job into \`running\` when appropriate.
5. Execute pending chunks in the task pool with bounded concurrency.
6. Mark partial failure or merge into the final transcript on full success.
7. Optionally remove chunk artifacts on \`cleanup-policy=on-success\`.

## Why this layer is isolated

- It keeps orchestration out of the CLI.
- It prevents infrastructure from inventing workflow transitions on its own.
- It centralizes the difference between fatal errors and reusable partial failures.

## Relevant files

${renderFileList(snapshot.applicationFiles)}
      `);
    },
  },
  {
    path: "evidence/modules/domain.md",
    title: "Domain Module Evidence",
    category: "module",
    summary: "Observed job lifecycle concepts, invariants, and domain file inventory.",
    sourcePaths: ["src/domain", "src/shared/errors.ts", "src/shared/paths.ts"],
    build(snapshot) {
      return buildPage(this, `
# Domain Module Evidence

This file is deterministic evidence for the domain layer.

## Main concepts

- \`Job\`: aggregate that owns job status transitions, compatibility checks, and exit code derivation.
- \`JobChunk\`: per-chunk lifecycle state.
- \`ChunkManifest\`: persisted chunk ordering and timing.
- Ports:
  - \`JobStore\`
  - \`MediaSegmenter\`
  - \`Transcriber\`
  - \`TranscriberBinding\`

## Observed invariants

- job-state version stays at \`1\`
- only valid status transitions are allowed
- resume compares \`resolvedInputPath\`, size, mtime, provider, signature, and chunk duration
- chunk failure remains reusable via \`partial_failed\`
- \`succeeded\` returns exit code \`0\`, \`partial_failed\` returns \`2\`, everything else returns \`1\`

## Relevant files

${renderFileList(snapshot.domainFiles)}
      `);
    },
  },
  {
    path: "evidence/modules/infrastructure.md",
    title: "Infrastructure Module Evidence",
    category: "module",
    summary: "Observed side-effect boundaries, design choices, and file inventory for infrastructure.",
    sourcePaths: ["src/infrastructure", "src/shared/process.ts", "src/shared/logger.ts"],
    build(snapshot) {
      return buildPage(this, `
# Infrastructure Module Evidence

This file is deterministic evidence for the infrastructure layer.

## Main areas

- **storage**: \`FileJobStore\` plus typed persistence records and mappers
- **media**: \`FFmpegMediaSegmenter\` and \`ffprobe\` wrappers
- **concurrency**: bounded task pool for chunk execution
- **providers**: fake/OpenAI adapters and configuration helpers

## Observed design choices

- \`FileJobStore\` serializes mutations through a queue so concurrent chunk completions do not corrupt \`job-state.json\`.
- Records and mappers isolate on-disk schema from in-memory objects.
- Media normalization happens before provider upload.
- Provider configuration stays outside the application use case.

## Relevant files

${renderFileList(snapshot.infrastructureFiles)}
      `);
    },
  },
  {
    path: "evidence/modules/providers.md",
    title: "Provider Adapter Evidence",
    category: "module",
    summary: "Observed provider matrix, signature rules, and adapter file inventory.",
    sourcePaths: ["src/infrastructure/providers", "src/cli/default-transcriber-binding-factory.ts"],
    build(snapshot) {
      return buildPage(this, `
# Provider Adapter Evidence

This file is deterministic evidence for the provider adapter layer.

## Supported providers

- \`fake\`: deterministic/offline test provider
- \`openai-whisper\`: fixed to \`whisper-1\`
- \`openai-transcription\`: supports OpenAI or Azure backends

## Observed signature strategy

Provider configuration contributes to a stable \`transcriberSignature\` used by resume compatibility checks. This prevents resuming a job with a different model, backend, endpoint, prompt, or language setting.

## Observed upload guards

- OpenAI-based providers estimate WAV size before upload.
- The CLI rejects chunk durations whose normalized audio would exceed the configured upload limit.

## Relevant files

${renderFileList(snapshot.providerFiles)}
      `);
    },
  },
  {
    path: "evidence/workflows/transcription-job.md",
    title: "Transcription Workflow Evidence",
    category: "workflow",
    summary: "Observed execution path from CLI input to final transcript output.",
    sourcePaths: ["src/cli", "src/application", "src/domain", "src/infrastructure"],
    build() {
      return buildPage(this, `
# Transcription Workflow Evidence

This file is deterministic evidence for the end-to-end transcription workflow.

\`\`\`mermaid
sequenceDiagram
  participant User
  participant CLI
  participant UseCase
  participant Store
  participant Segmenter
  participant Binding
  participant Provider
  participant Merge

  User->>CLI: run transcription command
  CLI->>CLI: parse args and load env
  CLI->>Binding: resolve provider binding
  CLI->>UseCase: execute
  UseCase->>Store: initialize or resume job
  alt new job
    UseCase->>Segmenter: segment media
    Segmenter-->>UseCase: manifest
    UseCase->>Store: persist manifest and hydrate chunks
  end
  UseCase->>Binding: create transcriber if pending chunks exist
  Binding-->>Provider: transcriber instance
  loop pending chunks
    UseCase->>Store: mark chunk running
    UseCase->>Provider: transcribe normalized WAV
    alt success
      UseCase->>Store: write chunk markdown and mark succeeded
    else failure
      UseCase->>Store: mark failed
    end
  end
  alt all chunks succeeded
    UseCase->>Merge: assemble transcript.md
    Merge->>Store: write final markdown
  else partial failure
    UseCase->>Store: mark partial_failed
  end
\`\`\`

## Observed exit paths

- Full success: final markdown written and exit code \`0\`
- Partial failure: reusable state persisted and exit code \`2\`
- Fatal error: job moves to \`fatal_error\` when possible and exit code \`1\`
      `);
    },
  },
  {
    path: "evidence/workflows/resume-semantics.md",
    title: "Resume Workflow Evidence",
    category: "workflow",
    summary: "Observed compatibility snapshot, retry behavior, and resume constraints.",
    sourcePaths: ["src/application/run-transcription-job-use-case.ts", "src/domain/entities/job.ts", "src/infrastructure/storage/file-job-store.ts"],
    build() {
      return buildPage(this, `
# Resume Workflow Evidence

This file is deterministic evidence for resume semantics.

## Snapshot fields

- \`resolvedInputPath\`
- \`inputSizeBytes\`
- \`inputMtimeMs\`
- \`provider\`
- \`transcriberSignature\`
- \`chunkDurationSeconds\`

## Observed rules

- If artifacts already exist and \`--resume\` is absent, the CLI fails fast.
- If \`--resume\` is present without persisted artifacts, the CLI also fails fast.
- Jobs in \`created\`, \`segmenting\`, or \`fatal_error\` are not resumable.
- Chunks in \`failed\` return to \`pending\`.
- Chunks left in \`running\` without \`finishedAt\` also return to \`pending\`.
- Completed chunks remain skipped.

## Why this evidence matters

These checks prevent silently mixing different providers, prompts, endpoints, or chunking strategies into the same persisted job.
      `);
    },
  },
  {
    path: "evidence/testing.md",
    title: "Testing Evidence",
    category: "quality",
    summary: "Observed test layers, coverage goals, and raw test file inventory.",
    sourcePaths: ["tests", "package.json", "README.md"],
    build(snapshot) {
      return buildPage(this, `
# Testing Evidence

This file is deterministic evidence for the repository's testing posture.

## Current shape

${countText("test files", snapshot.testFiles.length)}

## Main test layers

- unit tests for parser, config normalization, task pool, persistence mappers, and provider wrappers
- integration tests for the orchestration flow, file job store, CLI wiring, and provider-specific CLI behavior
- optional host-dependent verification for long input scenarios through \`npm run verify:long-input\`

## Coverage goals

- preserve \`manifest.json\` and \`job-state.json\` schema
- preserve exit codes \`0\`, \`1\`, and \`2\`
- prove resume no-op behavior for already succeeded jobs
- keep provider tests mockable without real network access

## Relevant files

${renderFileList(snapshot.testFiles)}
      `);
    },
  },
];
